server:
  port: 8080

spring:
  config:
    import: optional:file:../.env,optional:file:.env
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskflow}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      data-source-properties:
        sslMode: REQUIRED
        enabledTLSProtocols: TLSv1.2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
app:
  jwt:
    secret: ${APP_JWT_SECRET:VGhpc0lzQVNlY3VyZTMyaGFyQmFzZTY0S2V5VG9SZWFsbHlDaGFuZ2U=}
    exp-minutes: 240
