spring:
  datasource:
    url: jdbc:h2:file:./data/taskflow;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
